# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 623a6a10467cadf927bf96ed2e01494d308e20ab6cf1880d74b32a3ec671e882fd829078f95c9a3c7ef785776295843bf8816a8776fe004851a20cf09c0ab649

test:
  secret_key_base: ca5bf81ad7b7ff1540f4c1c5d9dda83183d0a7e68f1fea368caafcb4f4afa34f0452844a4ada188ff8a390ff0b274bc07437adb8431b994bc82b4a9c8f6708dc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
